//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playlists_songs
    {
        public int playlist_id { get; set; }
        public int song_id { get; set; }
        public int id { get; set; }
    
        public virtual playlists playlists { get; set; }
        public virtual songs songs { get; set; }
    }
}
