//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class songs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public songs()
        {
            this.playlists_songs = new HashSet<playlists_songs>();
        }
    
        public int id { get; set; }
        public string song_name { get; set; }
        public string album_name { get; set; }
        public Nullable<int> duration { get; set; }
        public byte[] song_cover { get; set; }
        public int user_id { get; set; }
        public string author_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<playlists_songs> playlists_songs { get; set; }
        public virtual users users { get; set; }
    }
}
